language: node_js

node_js:
  - node

install:
  - npm install

cache:
  directories:
    - node_modules

script:
  - npm run lint

deploy:
  if: branch = master
  provider: npm
  email: rn.wolfe@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
